# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170601_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('sl_no', models.IntegerField()),
                ('dot', models.DateTimeField()),
                ('branch', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=200)),
                ('snum', models.CharField(max_length=200)),
                ('can_name', models.CharField(max_length=200)),
                ('sdetail', models.CharField(max_length=200)),
                ('main_skills', models.TextField()),
                ('uname', models.CharField(max_length=200)),
                ('cus_name', models.CharField(max_length=200)),
                ('ep_num', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=200)),
                ('doi', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
                ('cont_num', models.IntegerField()),
                ('email_id', models.EmailField(max_length=200)),
                ('texp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rexp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cu_org', models.CharField(max_length=200)),
                ('cu_loc', models.CharField(max_length=200)),
                ('pref_loc', models.CharField(max_length=200)),
                ('cu_ctc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('exp_ctc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notice_period', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
    ]
