# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170716_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='cd1_doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='cd1_ep_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='cd1_js',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='cd1_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='cd2_doj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='cd2_ep_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='cd2_js',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='cd2_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='fb_pending',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='hr_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='hr_s_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='mr_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='mr_s_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='num_cv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='num_process',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='num_released',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='old_rgs_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='recruiter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='rgs_id_status',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='requirement',
            name='scr_rej',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='shortlist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='tr_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='tr_s_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
