# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170718_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='doi',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='dot',
            field=models.DateTimeField(null=True),
        ),
    ]
