# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170601_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingMasterTracker',
            fields=[
                ('sl_no', models.IntegerField()),
                ('dot', models.DateTimeField()),
                ('branch', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=200)),
                ('snum', models.CharField(max_length=200)),
                ('can_name', models.CharField(max_length=200)),
                ('sdetail', models.CharField(max_length=200)),
                ('main_skills', models.TextField()),
                ('uname', models.CharField(max_length=200)),
                ('cus_name', models.CharField(max_length=200)),
                ('ep_num', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
    ]
